Repository shadcn-ui/ui, pull requests merged in 2023-03, with the labels that each got.

#106 Unexpected lexical declaration in case block
  apps/www/hooks/use-toast.ts
Labels: area: component, component: toast

#50 feat(sheet): add sheet component
  apps/www/components/examples/index.tsx
  apps/www/components/examples/sheet/demo.tsx
  apps/www/components/examples/sheet/position.tsx
  apps/www/components/examples/sheet/size.tsx
  apps/www/components/ui/sheet.tsx
  apps/www/config/docs.ts
  apps/www/content/docs/primitives/sheet.mdx
Labels: area: component, component: sheet

#115 feat: add COMPONENTS_BASE_URL for development
  .changeset/khaki-roses-rule.md
  .changeset/nervous-knives-impress.md
  .github/workflows/prerelease-comment.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  apps/www/pages/api/components.json
  package.json
  packages/cli/README.md
  packages/cli/package.json
  packages/cli/src/utils/get-components.ts
  pnpm-lock.yaml
  turbo.json
Labels: 🚀 autorelease

#117 fix(@shadcn/ui): add start:dev command
  .github/workflows/prerelease-comment.yml
  packages/cli/.gitignore
  packages/cli/package.json
Labels: 🚀 autorelease

#118 Add warning for command
  .changeset/witty-apples-rule.md
  package.json
  packages/cli/src/index.ts
Labels: area: @shadcn/ui
