Repository shadcn-ui/ui, pull requests merged in 2024-03, with the labels that each got.

#2673 docs(next-installation): Fixed type error in Next.js installation by removing export from fontSans
  apps/www/content/docs/installation/next.mdx
Labels: documentation, automerge

#2610 [Feat]: Add Bug report and Feature request templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: area: roadmap

#2048 fix(components): Add "use client" directive to Toast
  apps/www/public/registry/styles/default/toast.json
  apps/www/public/registry/styles/new-york/toast.json
  apps/www/registry/default/ui/toast.tsx
  apps/www/registry/default/ui/use-toast.ts
  apps/www/registry/new-york/ui/toast.tsx
  apps/www/registry/new-york/ui/use-toast.ts
Labels: component: toast, area: roadmap, automerge

#133 feat(breadcrumb): add breadcrumb component
  apps/www/__registry__/index.tsx
  apps/www/content/docs/components/breadcrumb.mdx
  apps/www/lib/utils.ts
  apps/www/public/registry/index.json
  apps/www/public/registry/styles/default/breadcrumb.json
  apps/www/public/registry/styles/default/toast.json
  apps/www/public/registry/styles/new-york/breadcrumb.json
  apps/www/public/registry/styles/new-york/toast.json
  apps/www/registry/default/example/breadcrumb-demo.tsx
  apps/www/registry/default/example/breadcrumb-dropdown.tsx
  apps/www/registry/default/example/breadcrumb-ellipsis.tsx
  apps/www/registry/default/example/breadcrumb-link.tsx
  apps/www/registry/default/example/breadcrumb-responsive.tsx
  apps/www/registry/default/example/breadcrumb-separator.tsx
  apps/www/registry/default/ui/breadcrumb.tsx
  apps/www/registry/new-york/example/breadcrumb-demo.tsx
  apps/www/registry/new-york/example/breadcrumb-dropdown.tsx
  apps/www/registry/new-york/example/breadcrumb-ellipsis.tsx
  apps/www/registry/new-york/example/breadcrumb-link.tsx
  apps/www/registry/new-york/example/breadcrumb-responsive.tsx
  apps/www/registry/new-york/example/breadcrumb-separator.tsx
  apps/www/registry/new-york/ui/breadcrumb.tsx
  apps/www/registry/registry.ts
Labels: new component, area: roadmap

#2919 feat: add input-otp
  apps/www/__registry__/index.tsx
  apps/www/config/docs.ts
  apps/www/content/docs/components/input-otp.mdx
  apps/www/package.json
  apps/www/public/registry/index.json
  apps/www/public/registry/styles/default/input-otp.json
  apps/www/public/registry/styles/new-york/input-otp.json
  apps/www/registry/default/example/input-otp-controlled.tsx
  apps/www/registry/default/example/input-otp-demo.tsx
  apps/www/registry/default/example/input-otp-form.tsx
  apps/www/registry/default/example/input-otp-pattern.tsx
  apps/www/registry/default/example/input-otp-separator.tsx
  apps/www/registry/default/ui/input-otp.tsx
  apps/www/registry/new-york/example/input-otp-controlled.tsx
  apps/www/registry/new-york/example/input-otp-demo.tsx
  apps/www/registry/new-york/example/input-otp-form.tsx
  apps/www/registry/new-york/example/input-otp-pattern.tsx
  apps/www/registry/new-york/example/input-otp-separator.tsx
  apps/www/registry/new-york/ui/input-otp.tsx
  apps/www/registry/registry.ts
  pnpm-lock.yaml
  tailwind.config.cjs
Labels: new component, area: roadmap

#2937 docs: update changelog
  apps/www/components/announcement.tsx
  apps/www/config/docs.ts
  apps/www/content/docs/changelog.mdx
Labels: automerge

#3052 feat: switch input-otp to composition
  apps/www/content/docs/components/input-otp.mdx
  apps/www/package.json
  apps/www/public/registry/styles/default/input-otp.json
  apps/www/public/registry/styles/new-york/input-otp.json
  apps/www/registry/default/example/input-otp-controlled.tsx
  apps/www/registry/default/example/input-otp-demo.tsx
  apps/www/registry/default/example/input-otp-form.tsx
  apps/www/registry/default/example/input-otp-pattern.tsx
  apps/www/registry/default/example/input-otp-separator.tsx
  apps/www/registry/default/ui/input-otp.tsx
  apps/www/registry/new-york/example/input-otp-controlled.tsx
  apps/www/registry/new-york/example/input-otp-demo.tsx
  apps/www/registry/new-york/example/input-otp-form.tsx
  apps/www/registry/new-york/example/input-otp-pattern.tsx
  apps/www/registry/new-york/example/input-otp-separator.tsx
  apps/www/registry/new-york/ui/input-otp.tsx
  apps/www/styles/mdx.css
  pnpm-lock.yaml
Labels: enhancement, component: input-otp

#3134 chore(vaul): upgrade vaul version to a more recent
  apps/www/package.json
  pnpm-lock.yaml
Labels: area: www, automerge
